// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCebDrSemgNUKstjAL3saH_qjJq2q6Y9xk',
    appId: '1:1013393360300:web:fe6ffbf3a9e79429d5a609',
    messagingSenderId: '1013393360300',
    projectId: 'reddit-clone-8eb91',
    authDomain: 'reddit-clone-8eb91.firebaseapp.com',
    storageBucket: 'reddit-clone-8eb91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn3jgTJJd1QEuRQxZqLgkvzBFrYu2yijc',
    appId: '1:1013393360300:android:02181dd98bca7d94d5a609',
    messagingSenderId: '1013393360300',
    projectId: 'reddit-clone-8eb91',
    storageBucket: 'reddit-clone-8eb91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjO1zItIkE7HtVN_dF1EthfQzROYF72bw',
    appId: '1:1013393360300:ios:111ee5457efae0e5d5a609',
    messagingSenderId: '1013393360300',
    projectId: 'reddit-clone-8eb91',
    storageBucket: 'reddit-clone-8eb91.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjO1zItIkE7HtVN_dF1EthfQzROYF72bw',
    appId: '1:1013393360300:ios:111ee5457efae0e5d5a609',
    messagingSenderId: '1013393360300',
    projectId: 'reddit-clone-8eb91',
    storageBucket: 'reddit-clone-8eb91.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCebDrSemgNUKstjAL3saH_qjJq2q6Y9xk',
    appId: '1:1013393360300:web:4ec1c8cb1ebbb5c3d5a609',
    messagingSenderId: '1013393360300',
    projectId: 'reddit-clone-8eb91',
    authDomain: 'reddit-clone-8eb91.firebaseapp.com',
    storageBucket: 'reddit-clone-8eb91.firebasestorage.app',
  );
}
